/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystemapp;

import javax.swing.JFrame;

/**
 *
 * @author Al Azad
 */
public class TeachetMainUI extends javax.swing.JFrame {

    /**
     * Creates new form TeachetMainUI
     */
    public TeachetMainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        EmployeeRegistrationMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PaymentDetailsMenuItem = new javax.swing.JMenuItem();
        backMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(250, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystemapp/help1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("Teacher Details");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        EmployeeRegistrationMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeeRegistrationMenuItem.setText("Teacher registration");
        EmployeeRegistrationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeRegistrationMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(EmployeeRegistrationMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Teacher Payment");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PaymentDetailsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PaymentDetailsMenuItem.setText("Payment Details");
        PaymentDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentDetailsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PaymentDetailsMenuItem);

        jMenuBar1.add(jMenu2);

        backMenu.setText("Back");
        backMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMenuMouseClicked(evt);
            }
        });
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(backMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeRegistrationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeRegistrationMenuItemActionPerformed
        // TODO add your handling code here:
         TeachersUI teachersui = new TeachersUI();
        teachersui.show();
     this.hide();
        
    }//GEN-LAST:event_EmployeeRegistrationMenuItemActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_backMenuActionPerformed

    private void backMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMenuMouseClicked
        // TODO add your handling code here:
          HomePageUI homepageui = new HomePageUI();
        homepageui.show();
        this.hide();
    }//GEN-LAST:event_backMenuMouseClicked

    private void PaymentDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        TeacherReportView teacherReportView =new TeacherReportView();
        teacherReportView.show();
        
    }//GEN-LAST:event_PaymentDetailsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachetMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachetMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachetMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachetMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachetMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EmployeeRegistrationMenuItem;
    private javax.swing.JMenuItem PaymentDetailsMenuItem;
    private javax.swing.JMenu backMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
